FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml common-events/pom.xml billing-service/pom.xml ./
COPY common-events ./common-events
COPY billing-service ./billing-service
RUN mvn -q -pl common-events,billing-service -am package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/billing-service/target/billing-service-*.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]
