FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml common-events/pom.xml rental-service/pom.xml ./
COPY common-events ./common-events
COPY rental-service ./rental-service
RUN mvn -q -pl common-events,rental-service -am package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/rental-service/target/rental-service-*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
