FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml common-events/pom.xml notification-service/pom.xml ./
COPY common-events ./common-events
COPY notification-service ./notification-service
RUN mvn -q -pl common-events,notification-service -am package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/notification-service/target/notification-service-*.jar app.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "app.jar"]
