ALTER TABLE rentals ADD COLUMN IF NOT EXISTS return_mileage INTEGER;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS return_inspection_notes VARCHAR(2000);
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS settlement_closed BOOLEAN NOT NULL DEFAULT FALSE;
